szulinap/boldog/urls.py
from django.conf.urls import url
from boldog import views

# SET THE NAMESPACE!
app_name = 'boldog'

urlpatterns=[
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^register/$',views.register,name='register'),
    url(r'^welcome/$',views.welcome,name='welcome'),
    url(r'^user_logout/$',views.user_logout,name='user_logout'),
    url(r'^ajandek/$',views.ajandek,name='ajandek'),
    url(r'^feladat/$', views.feladat, name='feladat'),
    url(r'^failed/$', views.failed, name='failed'),
    url(r'^q1/$', views.q1, name='q1'),
    url(r'^q2_64738/$', views.q2_64738, name='q2_64738'),
    url(r'^q3_23491723/$', views.q3_23491723, name='q3_23491723'),
    url(r'^q4_98362527/$', views.q4_98362527, name='q4_98362527'),
    url(r'^by/$',views.by,name='by'),

]

szulinap/szulinap/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from boldog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^boldog/', include('boldog.urls')),
]


#use these directories for developer mode
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

szulinap/boldog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

# Create your models here.

class Counter(models.Model):
    Quiz = models.SmallIntegerField()

szulinap/boldog/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

szulinap/boldog/views.py
from django.shortcuts import render
from .forms import UserForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .models import Counter
# Create your views here.


counter = 0

def index(request):

    return render(request, 'boldog/index.html')

def register(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)

        # Check to see  form is valid
        if user_form.is_valid():

            user = user_form.save()  # Save User Form to Databas
            user.set_password(user.password)  # Hash the password
            user.save()  # Update with Hashed password
            registered = True  # Registration Successful!

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request, 'boldog/register.html',
                  {'user_form': user_form,
                   'registered': registered,
                   })




def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('boldog:welcome'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'boldog/login.html', {})


@login_required
def welcome(request):
    usern = request.user.username


    return render(request, 'boldog/welcome.html', {'username':usern})


@login_required
def feladat(request):

    return render(request, 'boldog/feladat.html')

@login_required
def q1(request):
    answere = request.GET.get("q")
    if answere == "e":
        return HttpResponseRedirect(reverse('boldog:q2_64738'))

    return render(request, 'boldog/q1.html')


@login_required
def q2_64738(request):
    a = request.GET.get("q2")
    print (a)
    if a == "g":
        return HttpResponseRedirect(reverse('boldog:q3_23491723'))

    return render(request, 'boldog/q2_64738.html')

@login_required
def q3_23491723(request):
    a = request.GET.get("q3")
    print (a)
    if a == "a":
        return HttpResponseRedirect(reverse('boldog:q4_98362527'))
    return render(request, 'boldog/q3_23491723.html')


@login_required
def q4_98362527(request):
    a = request.GET.get("q4")

    global counter
    if counter < 3:
        print(counter)
        if a == "ae":
            return HttpResponseRedirect(reverse('boldog:ajandek'))
        else:
            counter =+ 1
            return render(request, 'boldog/q4_98362527.html')

    return HttpResponseRedirect(reverse('boldog:failed'))


def failed(request):

    return render(request, 'boldog/failed.html')

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return render(request, 'boldog/login.html')

@login_required
def ajandek(request):
    usern = request.user.username
    return render(request, 'boldog/ajandek.html',{'username':usern})

def by(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return render(request, 'boldog/by.html')

szulinap/templates/boldog/ajandek.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/boldog.css' %}"/>
   <link href="https://fonts.googleapis.com/css?family=Kalam|Patrick+Hand" rel="stylesheet">
</head>
<body id="ajandek">


<div class="container" align="center">
<h1>WELLL DONE LÍVIKE:-)))) <br> ÜGYES VAGY!!! <br>
</h1>
    <br><br><br>

<img src="{% static 'images/voucher.png' %}" height="40%", width="40%" />
       <br><br><br>
    <h1>Beváltható Budapest területén <br> az általad választott szobában!</h1>

</div>

</body>
<script
  src="http://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



</html>

szulinap/templates/boldog/by.html
{% extends "boldog/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="container" align="center">
    <br><br><br>

    <h1>HAVE A GOOD DAY BRO!!!! </h1>

    <img src="{% static 'images/hand.jpg' %}" style=" border-radius: 50%;"/>



<br><br><br><br><br><br><br><br><br><br><br><br>




</div>
{% endblock %}

szulinap/templates/boldog/failed.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/boldog.css' %}"/>
   <link href="https://fonts.googleapis.com/css?family=Kalam|Patrick+Hand" rel="stylesheet">
</head>
<body id="q1">



<div class="container" align="center">
    <br><br><br><br>
<h1>SAJNOS EZ MOST NEM JÖTT ÖSSZE :(((</h1>
    <h1>DE NE AGGÓDJ JÖVŐRE IS LESZ KARÁCSONY, HEHEHE!!!</h1>

    <h1></h1>


</div>

<!--<a href="{% url 'boldog:by'%}"><button type="button" id="ajandek" class="btn btn-primary">VÉTEL VÉGE VE!!!<br>KÉREM KAPCSOLJA KI!!</button></a>
</div>-->

</body>
<script
  src="http://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



</html>

szulinap/templates/boldog/feladat.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/boldog.css' %}"/>
   <link href="https://fonts.googleapis.com/css?family=Kalam|Patrick+Hand" rel="stylesheet">
</head>
<body id="welcome">

<br><br><br><br>


 <div class="container" align="center">
<h1> </h1>
<br><br>
    <h3>Pár kérdésre kéne válaszolni. <br> Ha megadod a helyes választ (fontos, hogy csak kis betűket használj) akkor <br>
    automatikusan kapod a következő kérdést, <br> ha nem akkor a válaszod kitörlődik és maradsz az adott kérdésnél és újra próbálhatod maximum 3x.</h3>
     <br><br>
     <h3>Ha megcsinálod, akkor talán kapsz ajándékot is!</h3>
        <br>

         <h3>Viszont ha nem akkor csak két pofont :P!</h3>
        <br>
     <br><br>

<a href="{% url 'boldog:q1'%}"><button type="button" class="btn btn-primary">NA HALADJUNK!!!</button></a>

     <br><br>
    <img src="{% static 'images/dancing.gif' %}"/>
</div>


</body>
<script
  src="http://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



</html>

szulinap/templates/boldog/index.html
{% extends "boldog/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="container" align="center">



<br><br><br><br>
    <h1>Boldog Karácsonyt Lívike!!!</h1>

<br><br><br><br>

    <a href="{% url 'boldog:user_login'%}"><button type="button" class="btn btn-primary">KÉREM AZ AJÁNDÉKOT!!!!!</button></a><br><br>
   <a href="{% url 'boldog:register'%}"><button type="button" class="btn btn-primary">REGISZTRÁLOK AZ AJÁNDÉKÉRT!</button></a>

</div>
<br><br><br>

{% endblock %}

szulinap/templates/boldog/login.html
{% extends "boldog/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container text-center">
<h1>Jelentkezzééé be szépen!!!</h1>
<h1>VAGY NYOMÁS <a href="{% url 'boldog:register' %}">REGISZTRÁÁNI</a></h1>

</div>
<div class="container">
        <div class="card card-container">
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="{% static 'images/monkey.jpg' %}" />
            <p id="profile-name" class="profile-name-card"></p>
            <form class="form-signin" method="post" action="{% url 'boldog:user_login' %}">
                  {% csrf_token %}

                <input type="text" name="username" id="inputEmail" class="form-control" placeholder="Username" value=""required autofocus>
                <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" value="" required>
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Login</button>
            </form>

                </div>

            <!-- /form -->

        </div><!-- /card-container -->
    </div><!-- /container -->

{% endblock %}

szulinap/templates/boldog/q1.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/boldog.css' %}"/>
   <link href="https://fonts.googleapis.com/css?family=Kalam|Patrick+Hand" rel="stylesheet">
</head>
<body id="q1">



<div class="container" align="center">
    <br><br><br><br>
<h1>Quiz 1</h1>

 <img src="{% static 'images/q3.gif' %}" />
<br>
    <br>
    <br>
    <br>

   <form method="GET" action="">
        <input type="text" name="q" placeholder="Melyik kép passzol a '?' helyére" value=""/>
       <br>
        <input type="submit" value="Válasz küldése"/>


    </form>

</div>

<!--<a href="{% url 'boldog:by'%}"><button type="button" id="ajandek" class="btn btn-primary">VÉTEL VÉGE VE!!!<br>KÉREM KAPCSOLJA KI!!</button></a>
</div>-->

</body>
<script
  src="http://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



</html>

szulinap/templates/boldog/q2_64738.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/boldog.css' %}"/>
   <link href="https://fonts.googleapis.com/css?family=Kalam|Patrick+Hand" rel="stylesheet">
</head>
<body id="q1">

<div class="container" align="center">
<br><br><br>
    <h1>Quiz 2</h1>
    <br><br><br>
 <img src="{% static 'images/q4.gif' %}" />
    <br><br><br>


   <form method="GET" action="">
        <input type="text" name="q2" placeholder="Ide írd a választ" value=""/>
       <br>
        <input type="submit" value="Válasz küldése"/>


    </form>

</div>

<!--<a href="{% url 'boldog:by'%}"><button type="button" id="ajandek" class="btn btn-primary">VÉTEL VÉGE VE!!!<br>KÉREM KAPCSOLJA KI!!</button></a>
</div>-->

</body>
<script
  src="http://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



</html>

szulinap/templates/boldog/q3_23491723.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/boldog.css' %}"/>
   <link href="https://fonts.googleapis.com/css?family=Kalam|Patrick+Hand" rel="stylesheet">
</head>
<body id="q1">


<div class="container" align="center">
    <br><br><br><br>
  <h1>Quiz 3</h1>
    <br><br>
<img src="{% static 'images/q5.gif' %}" />

    <br><br>

     <form method="GET" action="">
        <input type="text" name="q3" placeholder="Ide írd a választ" value=""/><br>

        <input type="submit" value="Válasz küldése"/>


    </form>


<!--<a href="{% url 'boldog:by'%}"><button type="button" id="ajandek" class="btn btn-primary">VÉTEL VÉGE VE!!!<br>KÉREM KAPCSOLJA KI!!</button></a>
</div>-->

</body>
<script
  src="http://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



</html>

szulinap/templates/boldog/q4_98362527.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/boldog.css' %}"/>
   <link href="https://fonts.googleapis.com/css?family=Kalam|Patrick+Hand" rel="stylesheet">
</head>
<body id="q1">


<div class="container" align="center">
  <h1>Quiz 4</h1>
    <h3>Melyik 2! kocka hajtható a kiterítettből? <br> Mind a kettőt meg kell adni, szóköz nélkül kisbetűvel egybe írva (pl. gm)!!!!</h3>
<img src="{% static 'images/kocka.png' %}" />

    <br><br>

     <form method="GET" action="">
        <input type="text" name="q4" placeholder="pl: gh" value=""/>
         <br>
        <input type="submit" value="Válasz küldése"/>


    </form>


<!--<a href="{% url 'boldog:by'%}"><button type="button" id="ajandek" class="btn btn-primary">VÉTEL VÉGE VE!!!<br>KÉREM KAPCSOLJA KI!!</button></a>
</div>-->

</body>
<script
  src="http://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



</html>

szulinap/templates/boldog/q5_74653728.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/boldog.css' %}"/>
   <link href="https://fonts.googleapis.com/css?family=Kalam|Patrick+Hand" rel="stylesheet">
</head>
<body id="q1">


<div class="container" align="center">
  <h1>Quiz 5</h1>
<img src="{% static 'images/q5.gif' %}" />

    <br><br>

     <form method="GET" action="">
        <input type="text" name="q5" placeholder="Ide írd a választ" value=""/>
        <input type="submit" value="Válasz küldése"/>


    </form>


<!--<a href="{% url 'boldog:by'%}"><button type="button" id="ajandek" class="btn btn-primary">VÉTEL VÉGE VE!!!<br>KÉREM KAPCSOLJA KI!!</button></a>
</div>-->

</body>
<script
  src="http://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



</html>

szulinap/templates/boldog/register.html
{% extends "boldog/base.html" %}
{% load staticfiles %}
{% block body_block %}


<div class="container" align="center">

      {% if registered %}

    <br><br><br><br><br><br><br>
    <h2>TÜNDÉR VAGY, MOST HÚZZÁ OSZT LÉPJÉ BE!!!</h2>
    <h3><a href="{% url 'boldog:user_login' %}">IDE KATTINGASSÁÁÁ</a> </h3>
      {% else %}


        </div>
 <div class="container text-center">
    <h1>RENDES KIDLÁNY VAGY TE, REGISZTRÁJÁÁ SZÉPEN!!!</h1>
</div>
<div class="container">
        <div class="card card-container">
        <form enctype="multipart/form-data" method="POST" class="form-signin">
          {% csrf_token %}
          {{ user_form.as_p }}
  <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign Up</button>

        </form>


{% endif %}
{% endblock %}

szulinap/templates/boldog/welcome.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/boldog.css' %}"/>
   <link href="https://fonts.googleapis.com/css?family=Kalam|Patrick+Hand" rel="stylesheet">
</head>
<body id="welcome">

<br><br><br><br>


 <div class="container" align="center">
<h1>NA VÉGRE ELJUTOTTÁÁÁ IDÁIG!</span> </h1>
<br><br>
    <h3>Sajnos először fel kell mérjük mit tudsz, hogy tényleg érdemes e beinvesztálni az ajándékra. </h3>
     <h3>Felelslegesen nem szórjuk a pénzt, remélem ezt megérted!</h3>

     <br><br>

<a href="{% url 'boldog:feladat'%}"><button type="button" class="btn btn-primary">NA LÁSSAM MI EZ A HÜLYESÉG</button></a>

     <br><br>
    <img src="{% static 'images/dancing.gif' %}"/>
</div>


</body>
<script
  src="http://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



</html>